# - name: Copy mongodb repo
#   ansible.builtin.copy:
#     src: mongodb.repo
#     dest: /etc/yum.repos.d/mongodb.repo
  
# - name: Install mongodb
#   ansible.builtin.package:
#     name: mongodb-org
#     state: present

# - name: start and enable mongodb
#   ansible.builtin.service:
#     name: mongod
#     state: started
#     enabled: yes

# - name: allow remote conncections
#   ansible.builtin.replace:
#     path: /etc/mongod.conf
#     regexp: '127.0.0.1'
#     replace: '0.0.0.0'

# - name: start and enable mongodb
#   ansible.builtin.service:
#     name: mongod
#     state: restarted

- name: Set up MongoDB 7.0 repo for RHEL 9
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/mongodb-org-7.0.repo
    content: |
      [mongodb-org-7.0]
      name=MongoDB Repository
      baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
      gpgcheck=1
      enabled=1
      gpgkey=https://pgp.mongodb.com/server-7.0.asc

- name: Install required dependencies
  ansible.builtin.package:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present

- name: Clean DNF cache
  ansible.builtin.command: dnf clean all

- name: Rebuild DNF cache
  ansible.builtin.command: dnf makecache

- name: Install MongoDB
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Enable and start MongoDB service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Allow remote MongoDB connections
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127\.0\.0\.1'
    replace: '0.0.0.0'

- name: Restart MongoDB after config change
  ansible.builtin.service:
    name: mongod
    state: restarted
